"use client";
import { useMemo } from "react";
import { applyMajorProjectToQuote } from "../lib/major-project";
import type { ProcessingRequirements, QuoteRecord } from "../lib/quote-record";
import { getOrderProcessing } from "../lib/order-processing";
import { getIncludedEquipmentRows } from "../lib/proposal-commercial-summary";
import { prefillStarlinkRates, requiredProcessingRates, normalizeProcessingRequirements, missingProcessingRequirements } from "../lib/processing-requirements";

export function ProcessingRequirementsForm({ quote: source, onChange, onEditItems }: {
  quote: QuoteRecord; onChange: (updater: (quote: QuoteRecord) => QuoteRecord) => void; onEditItems: () => void;
}) {
  const quote = useMemo(() => source.metadata.workflowMode === "major_project" && source.majorProject?.enabled ? applyMajorProjectToQuote(source) : source, [source]);
  const value = normalizeProcessingRequirements(quote.orderProcessing?.requirements);
  const missing = missingProcessingRequirements(quote);
  const rows = quote.sections.sectionB.enabled ? getIncludedEquipmentRows(quote) : [];
  const update = (patch: Partial<ProcessingRequirements>) => onChange(draft => { draft.orderProcessing = { ...getOrderProcessing(draft), requirements: { ...normalizeProcessingRequirements(draft.orderProcessing?.requirements), ...patch } }; return draft; });
  const updateOrder = (patch: Partial<NonNullable<QuoteRecord["orderProcessing"]>>) => onChange(draft => { draft.orderProcessing = { ...getOrderProcessing(draft), ...patch }; return draft; });
  return <section className="builder-panel" aria-label="Required quote information">
    <h2 className="builder-title">Required quote information</h2>
    <p>Complete these details before saving or creating the quote. Confirm every choice, including items that do not apply.</p>
    {missing.length > 0 ? <div className="rq-order-checklist" role="status"><strong>{missing.length} required details remaining</strong><ul>{missing.map(item => <li key={item}>{item}</li>)}</ul></div> : <p className="rq-ready">Required quote information complete</p>}
    <div className="rq-detail-fields">
      <label className="builder-field"><span>Customer</span><input readOnly value={quote.customer.name} /></label>
      <label className="builder-field"><span>Sub account applicable?</span><select value={value.subAccountStatus} onChange={e => update({ subAccountStatus: e.target.value as ProcessingRequirements["subAccountStatus"] })}><option value="pending">Choose an answer</option><option value="yes">Yes</option><option value="no">No / not applicable</option></select></label>
      {value.subAccountStatus === "yes" && <label className="builder-field"><span>Sub account name / ID</span><input required value={value.subAccount} onChange={e => update({ subAccount: e.target.value })} /></label>}
      <label className="builder-field"><span>Data Plan/Pool</span><input required value={quote.orderProcessing?.dataPlanDetails || ""} placeholder="Plan / pool name and allowance, or Not applicable" onChange={e => onChange(draft => { draft.orderProcessing = { ...getOrderProcessing(draft), dataPlanDetails: e.target.value }; return draft; })} /></label>
      <label className="builder-field"><span>Corporate pricing?</span><select value={value.corporatePricing} onChange={e => update(e.target.value === "no" ? prefillStarlinkRates({ ...value, corporatePricing: "no" }) : { corporatePricing: e.target.value as ProcessingRequirements["corporatePricing"] })}><option value="pending">Choose an answer</option><option value="yes">Yes</option><option value="no">No — specify rates below</option></select></label>
      {value.corporatePricing === "yes" && <label className="builder-field"><span>Corporate pricing reference (optional)</span><input value={value.corporatePricingReference} onChange={e => update({ corporatePricingReference: e.target.value })} placeholder="Agreement / rate card" /></label>}
    </div>
    {value.corporatePricing === "no" && <div className="rq-order-section"><p>Editable defaults from the Starlink-only price sheet dated December 29, 2025. Review these rates for this order.</p><div className="rq-detail-fields"><label className="builder-field"><span>Starlink support default</span><select value={value.starlinkService} onChange={e => update({ starlinkService: e.target.value as ProcessingRequirements["starlinkService"], rates: { ...value.rates, managementSupport: { status: "priced", amount: e.target.value === "mini_vehicle" ? 5 : 10, basis: "per month" } } })}><option value="fixed">Fixed location — $10/month</option><option value="mini_vehicle">Mini vehicle — $5/month</option></select></label><button type="button" className="rq-button" onClick={() => update(prefillStarlinkRates(value, true))}>Reset to sheet prices</button></div></div>}
    {value.corporatePricing === "no" && <label className="builder-field"><span>Non-corporate pricing structure</span><select value={value.pricingStructure} onChange={e => update({ pricingStructure: e.target.value as ProcessingRequirements["pricingStructure"] })}><option value="pending">Choose individual or pool</option><option value="individual">Individual: TAC, 50GB, 500GB, overages and support</option><option value="pool">Pool: Pool TAC and management/support</option></select></label>}
    {value.corporatePricing === "no" && value.pricingStructure !== "pending" && <fieldset className="rq-order-section"><legend>Required non-corporate pricing</legend><p>Confirm the agreed rate and billing basis for each item. Use Line Items for charges included in the quote totals.</p>{requiredProcessingRates(value).map(({ key, label }) => <div key={key} className="rq-detail-fields">
      <label className="builder-field"><span>{label}</span><select value={value.rates[key].status} onChange={e => update({ rates: { ...value.rates, [key]: { ...value.rates[key], status: e.target.value } } })}><option value="pending">Choose an answer</option><option value="priced">Specify price</option><option value="included">Included</option><option value="not_applicable">Not applicable</option></select></label>
      {value.rates[key].status === "priced" && <><label className="builder-field"><span>{label} price ({quote.metadata.currencyCode})</span><input type="number" min="0" step="0.01" required value={value.rates[key].amount ?? ""} onChange={e => update({ rates: { ...value.rates, [key]: { ...value.rates[key], amount: e.target.value === "" ? null : Number(e.target.value) } } })} /></label><label className="builder-field"><span>{label} billing basis</span><input required value={value.rates[key].basis} onChange={e => update({ rates: { ...value.rates, [key]: { ...value.rates[key], basis: e.target.value } } })} /></label></>}
    </div>)}</fieldset>}
    <div className="rq-order-section"><h3>Equipment needed, quantity and pricing</h3>
      {!rows.length && <label className="builder-field"><span>Equipment needed?</span><select value={value.equipmentRequired} onChange={e => update({ equipmentRequired: e.target.value as ProcessingRequirements["equipmentRequired"] })}><option value="pending">Choose an answer</option><option value="yes">Yes — add equipment in Line Items</option><option value="no">No equipment needed</option></select></label>}
      <button type="button" className="rq-button" onClick={onEditItems}>Add / edit equipment in Line Items</button>
      {rows.map(row => <div key={row.id} className="rq-order-section"><strong>{row.itemName}</strong><p>Qty {row.quantity} · Unit price {new Intl.NumberFormat("en-US", { style: "currency", currency: quote.metadata.currencyCode || "USD" }).format(row.unitPrice)} · Total {new Intl.NumberFormat("en-US", { style: "currency", currency: quote.metadata.currencyCode || "USD" }).format(row.totalPrice)}</p><div className="rq-detail-fields">
        <label className="builder-field"><span>{row.itemName}: assembly?</span><select value={value.equipment[row.id]?.kind || "pending"} onChange={e => update({ equipment: { ...value.equipment, [row.id]: { assemblyDetails: value.equipment[row.id]?.assemblyDetails || "", kind: e.target.value as "pending" | "assembly" | "standalone" } } })}><option value="pending">Choose an answer</option><option value="assembly">Yes — assembly</option><option value="standalone">No — standalone item</option></select></label>
        {value.equipment[row.id]?.kind === "assembly" && <label className="builder-field"><span>Assembly details (optional)</span><input value={value.equipment[row.id].assemblyDetails} onChange={e => update({ equipment: { ...value.equipment, [row.id]: { ...value.equipment[row.id], assemblyDetails: e.target.value } } })} placeholder="Assembly number / included parts" /></label>}
      </div></div>)}
    </div>
    <div className="rq-order-section"><h3>Service, shipping and contacts</h3><div className="rq-detail-fields">
      <label className="builder-field"><span>Opt in or out of overages</span><select value={quote.orderProcessing?.overageOptIn || "pending"} onChange={e => updateOrder({ overageOptIn: e.target.value as NonNullable<QuoteRecord["orderProcessing"]>["overageOptIn"] })}><option value="pending">Choose an answer</option><option value="yes">Opt in</option><option value="no">Opt out</option><option value="not_applicable">Not applicable</option></select></label>
      <label className="builder-field"><span>Public IP?</span><select value={value.publicIp} onChange={e => update({ publicIp: e.target.value as ProcessingRequirements["publicIp"] })}><option value="pending">Choose an answer</option><option value="yes">Yes</option><option value="no">No</option></select></label>
      <label className="builder-field"><span>Shipping required?</span><select value={quote.orderProcessing?.shippingRequired || "pending"} onChange={e => updateOrder({ shippingRequired: e.target.value as NonNullable<QuoteRecord["orderProcessing"]>["shippingRequired"] })}><option value="pending">Choose an answer</option><option value="yes">Yes</option><option value="no">No shipping needed</option></select></label>
      {quote.orderProcessing?.shippingRequired === "yes" && <>
        <label className="builder-field"><span>Shipping address</span><textarea rows={3} value={(quote.shippingSameAsBillTo ? quote.billTo.lines : quote.shipTo.lines).join("\n")} onChange={e => onChange(draft => { const shipping = draft.shippingSameAsBillTo ? draft.billTo : draft.shipTo; shipping.lines = e.target.value.split("\n"); return draft; })} /></label>
        <label className="builder-field"><span>Shipping contact name</span><input value={(quote.shippingSameAsBillTo ? quote.billTo.attention : quote.shipTo.attention) || ""} onChange={e => onChange(draft => { const shipping = draft.shippingSameAsBillTo ? draft.billTo : draft.shipTo; shipping.attention = e.target.value; return draft; })} /></label>
        <label className="builder-field"><span>Shipping contact phone</span><input type="tel" value={quote.orderProcessing.shippingContactPhone} onChange={e => updateOrder({ shippingContactPhone: e.target.value })} /></label>
      </>}
      <label className="builder-field"><span>Service address</span><textarea rows={3} value={quote.customer.addressLines.join("\n")} onChange={e => onChange(draft => { draft.customer.addressLines = e.target.value.split("\n"); return draft; })} /></label>
      <label className="builder-field"><span>POC name</span><input value={quote.customer.contactName} onChange={e => onChange(draft => { draft.customer.contactName = e.target.value; return draft; })} /></label>
      <label className="builder-field"><span>POC phone number</span><input type="tel" value={quote.customer.contactPhone} onChange={e => onChange(draft => { draft.customer.contactPhone = e.target.value; return draft; })} /></label>
      <label className="builder-field"><span>Special instructions</span><textarea rows={3} value={quote.orderProcessing?.notes || ""} placeholder="Instructions for fulfillment, or None" onChange={e => updateOrder({ notes: e.target.value })} /></label>
    </div></div>
  </section>;
}
