export type CatalogItemKind = "equipment" | "service";

export type CatalogItem = {
  id: string;
  kind: CatalogItemKind;
  label: string;
  category: string;
  source: string;
  defaultUnitPrice: number;
  unitLabel?: string;
  terminalType?: string;
  partNumber?: string;
  description?: string;
};

export const equipmentCatalog: CatalogItem[] = [
  {
    id: "perf-kit",
    kind: "equipment",
    label: "Performance G3",
    category: "Terminal",
    source: "Starlink hardware pricing",
    defaultUnitPrice: 1999,
    terminalType: "Performance G3",
    description: "Rugged enterprise kit for harsh environments and critical sites.",
  },
  {
    id: "standard-kit",
    kind: "equipment",
    label: "Standard V4",
    category: "Terminal",
    source: "Starlink hardware pricing",
    defaultUnitPrice: 599,
    terminalType: "Standard V4",
    description: "Default fixed-site Starlink hardware option for mainstream business deployments.",
  },
  {
    id: "mini-kit",
    kind: "equipment",
    label: "Mini G1",
    category: "Terminal",
    source: "Starlink hardware pricing",
    defaultUnitPrice: 499,
    terminalType: "Mini G1",
    description: "Portable, low-power Starlink option for mobile or temporary deployments.",
  },
  {
    id: "pipe-adapter",
    kind: "equipment",
    label: "Pole Mount Adapter",
    category: "Mount Adapter",
    source: "Mounting accessories",
    defaultUnitPrice: 75,
    description: "Adapter used to connect terminal hardware to pole-mounted structures.",
  },
  {
    id: "perf-pipe-adapter",
    kind: "equipment",
    label: "Performance G3 Pole Mount Adapter",
    category: "Mount Adapter",
    source: "Mounting accessories",
    defaultUnitPrice: 75,
    description: "Pole mount adapter for Performance G3 deployments.",
  },
  {
    id: "mini-pole-mount",
    kind: "equipment",
    label: "Mini G1 Pole Mount",
    category: "Mount",
    source: "Mounting accessories",
    defaultUnitPrice: 85,
    description: "Pole mount option intended for Mini G1 deployments.",
  },
  {
    id: "cable-50m",
    kind: "equipment",
    label: "50 Meter Starlink Cable",
    category: "Cable",
    source: "Accessory catalog",
    defaultUnitPrice: 150,
    description: "Extended cable run for remote or rooftop terminal placement.",
  },
  {
    id: "savage-case",
    kind: "equipment",
    label: "Savage Case with Charger",
    category: "Accessory",
    source: "Accessory catalog",
    defaultUnitPrice: 325,
    description: "Portable protective case package for field-ready Starlink transport and charging.",
  },
  {
    id: "non-pen-mount",
    kind: "equipment",
    label: "Non-Pen Mount",
    category: "Mount",
    source: "Mounting accessories",
    defaultUnitPrice: 500,
    description: "Non-penetrating mount option for fixed-site deployments.",
  },
  {
    id: "cellular-router-industrial",
    kind: "equipment",
    label: "Industrial LTE Router",
    category: "Router",
    source: "Connectivity hardware",
    defaultUnitPrice: 795,
    description: "Field router for LTE/UniSIM primary or backup connectivity.",
  },
  {
    id: "dual-wan-router",
    kind: "equipment",
    label: "Dual-WAN Router",
    category: "Router",
    source: "Connectivity hardware",
    defaultUnitPrice: 995,
    description: "Router for Starlink plus LTE failover or blended connectivity packages.",
  },
  {
    id: "install-materials-kit",
    kind: "equipment",
    label: "Install Materials Kit",
    category: "Install Materials",
    source: "Install materials",
    defaultUnitPrice: 350,
    description: "Standard cable management, mounting hardware, weatherproofing, and job-site materials allowance.",
  },
  {
    id: "standoff-mount",
    kind: "equipment",
    label: "Standoff Mount",
    category: "Mount",
    source: "Mounting accessories",
    defaultUnitPrice: 50,
    description: "Stand-off mount option for select installs.",
  },
];

export const sectionACatalog: CatalogItem[] = [
  {
    id: "pool-500gb",
    kind: "service",
    label: "500GB US Pool for Starlink Service",
    category: "Pool Plan",
    source: "Standard pricing",
    defaultUnitPrice: 200,
    unitLabel: "pool",
  },
  {
    id: "pool-1tb",
    kind: "service",
    label: "1TB US Pool for Starlink Service",
    category: "Pool Plan",
    source: "Quick add",
    defaultUnitPrice: 280,
    unitLabel: "pool",
  },
  {
    id: "pool-3tb",
    kind: "service",
    label: "3TB US Pool for Starlink Service",
    category: "Pool Plan",
    source: "Standard pricing",
    defaultUnitPrice: 900,
    unitLabel: "pool",
  },
  {
    id: "pool-6tb",
    kind: "service",
    label: "6TB US Pool for Starlink Service",
    category: "Pool Plan",
    source: "Standard pricing",
    defaultUnitPrice: 1650,
    unitLabel: "pool",
  },
  {
    id: "block-50gb",
    kind: "service",
    label: "50GB Data Block",
    category: "Per Kit Data",
    source: "Standard pricing",
    defaultUnitPrice: 30,
    unitLabel: "block",
  },
  {
    id: "block-500gb",
    kind: "service",
    label: "500GB Data Block",
    category: "Per Kit Data",
    source: "Standard pricing",
    defaultUnitPrice: 132,
    unitLabel: "block",
  },
  {
    id: "block-1tb",
    kind: "service",
    label: "1TB Data Block",
    category: "Per Kit Data",
    source: "Quick add",
    defaultUnitPrice: 260,
    unitLabel: "block",
  },
  {
    id: "terminal-access-fee",
    kind: "service",
    label: "Terminal Access Fee",
    category: "Recurring Fee",
    source: "Default pricing",
    defaultUnitPrice: 45,
    unitLabel: "kit",
  },
  {
    id: "unisim-managed-lte",
    kind: "service",
    label: "UniSIM Managed LTE Service",
    category: "LTE Service",
    source: "Standard pricing",
    defaultUnitPrice: 85,
    unitLabel: "line",
    description: "Managed cellular connectivity line for LTE primary or backup service.",
  },
  {
    id: "lte-backup-service",
    kind: "service",
    label: "LTE Backup Connectivity",
    category: "LTE Service",
    source: "Standard pricing",
    defaultUnitPrice: 65,
    unitLabel: "site",
    description: "Monthly LTE backup service for sites using Starlink as primary connectivity.",
  },
  {
    id: "pool-overage",
    kind: "service",
    label: "Overage: Per 1.0 GB",
    category: "Pool Overage",
    source: "Standard pricing",
    defaultUnitPrice: 0.55,
    unitLabel: "GB",
  },
  {
    id: "support-included",
    kind: "service",
    label: "iNet Customer Support",
    category: "Support",
    source: "Standard pricing",
    defaultUnitPrice: 0,
    description: "24/7 support, portal access, and reporting included with service.",
  },
];
