import { createDefaultIntegrationState } from "@/app/lib/crm";
import type { QuoteRecord } from "@/app/lib/quote-record";

export const sampleQuoteRecord: QuoteRecord = {
  metadata: {
    proposalNumber: "RCT001",
    proposalDate: "April 2, 2026",
    revisionVersion: "1.0",
    documentTitle: "Budgetary Estimate",
    documentSubtitle: "Managed Communications Services",
    customerShortName: "CZ USA",
    customerProvider: "Starlink",
    currencyCode: "USD",
    status: "draft",
    quoteType: "purchase",
    ownerUserId: "nick-panyard",
    ownerName: "Nick Panyard",
    accountId: "acct-cz-usa",
    accountName: "CZ USA",
    lastTouchedAt: "2026-04-17T19:00:00.000Z",
  },
  documentation: {
    proposalTitle: "CZ USA",
    proposalDateLabel: "April 2, 2026",
    proposalNumberLabel: "RCT001",
    customerAddressHeading: "Customer Address",
    inetAddressHeading: "iNet Address",
    preparedByLabel: "Prepared By",
    inetSalesHeading: "iNet",
    billToHeading: "Bill To",
    shipToHeading: "Ship To",
  },
  approval: {
    heading: "Approve and Authorize",
    signatureLabel: "Signature",
    customerNameLabel: "Customer Name",
    dateLabel: "Date",
    approvalNote: "Customer Name:",
  },
  terms: {
    generalStarlinkServiceTermsTitle: "General Starlink Service Terms",
    generalStarlinkServiceTerms: [
      '1. “Local” service is for land based Starlink Services.',
      '2. Prices may be subject to change with 30 Day notice due to SpaceX/Starlink pricing plan modifications.',
      '3. “Opt In” and “Opt Out” Requirements:',
      'a. If terminal is "opted in" overages will be added at 50GB increments.',
      'i. Pool Plan Kits must be “Opt In”.',
      'b. If terminal is "opted out", upon exceeded allotted subscription, terminal will be throttled at 1024 kbps down and 512 kbps up.',
      '4. Automatic 50Gb overages blocks will not change subscription and will not repeat unless subscription allotment is exceeded in that month.',
      '5. Plan Changes and Requests:',
      'a. All plan changes take effect on the 1st day of the month following the change.',
    ],
    pricingTermsTitle: "Pricing Terms and Conditions",
    pricingTerms: [
      'Pricing for Pool for Starlink Service is based upon a 12 Month Term upon date of agreement between both parties.',
      'Term for individual Kits is specific to individual Service Order of that kit.',
      'Starlink reserves the right to modify its pricing at any time with 30 days’ notice prior to the change taking effect.',
      'This quote is valid for 30 days from creation date.',
      'Pricing is exclusive of all civil works, applicable taxes or tariffs.',
      'Shipping is FOB unless otherwise stated in this proposal.',
      'Payment terms NET 30 days from invoice date unless stated otherwise in Master Service Agreement.',
      'Pricing is in US Dollars.',
    ],
  },
  customer: {
    name: "CZ USA",
    logoText: "CZ USA",
    contactName: "Scott Duncan",
    contactPhone: "913-413-1793",
    contactEmail: "scott@cz-usa.com",
    addressLines: ["PO Box 171073", "Kansas City, Kansas 66117", "United States"],
  },
  inet: {
    name: "iNet",
    contactName: "Nick Panyard",
    contactPhone: "919-864-5912",
    contactEmail: "nick.panyard@inetlte.com",
    addressLines: ["Galleria Tower 2", "5051 Westheimer Road, Suite 1700", "Houston, TX 77056"],
  },
  billTo: {
    companyName: "CZ USA",
    attention: "Scott Duncan",
    lines: ["PO Box 171073", "Kansas City, Kansas 66117", "United States"],
  },
  shipTo: {
    companyName: "CZ USA",
    attention: "Scott Duncan",
    lines: ["PO Box 171073", "Kansas City, Kansas 66117", "United States"],
  },
  shippingSameAsBillTo: true,
  executiveSummary: {
    enabled: true,
    heading: "Executive Summary",
    customerContext: "Prepared for CZ USA to review Starlink managed communications services, hardware, and field services needed for deployment.",
    body: "This budgetary estimate outlines the proposed commercial structure for Starlink managed communications services and related equipment. Section A captures the Starlink service schedule, while Section B covers hardware and accessories. Additional terms and approval details are included at the end of this estimate.",
    paragraphs: [
      "Prepared for CZ USA to review Starlink managed communications services, hardware, and field services needed for deployment.",
      "This budgetary estimate outlines the proposed commercial structure for Starlink managed communications services and related equipment. Section A captures the Starlink service schedule, while Section B covers hardware and accessories. Additional terms and approval details are included at the end of this estimate.",
    ],
  },
  sections: {
    sectionA: {
      enabled: true,
      allowLineAdd: true,
      allowLineRemove: true,
      allowReorder: true,
      builderLabel: "Monthly service pricing",
      mode: "pool",
      title: "U.S Pool Starlink Pricing Schedule",
      introText: "The pricing provided in the following table is based upon 12 Month Term.",
      explanatoryParagraphs: [
        "Pool for Starlink Service: The Pool is a monthly service for all selected Starlink Kits, serviced and monitored by iNet, with a fixed data allotment. The Kits will share the pool and consume data as required by each individual site. The Kits will not be constrained by an individual (per-site) data allotment.",
        "The data pool is reset at the end of the month; unused data does not carry over into the next month.",
        "Overage: Cost per 1.0 GB of usage more than the pool data allotment. The total overage fee is invoiced the following month in which they are incurred.",
        "Terminal Access Fee: Starlink monthly fee per Active Starlink kit in the pool.",
      ],
      termMonths: 12,
      poolRows: [
        {
          id: "a_pool_500gb",
          rowType: "service",
          description: "3 TB, U.S. Pool for Starlink Service",
          quantity: 1,
          unitLabel: "pool",
          unitPrice: 1200,
          monthlyRate: 1200,
          totalMonthlyRate: 1200,
          sourceLabel: "Standard pricing",
        },
        {
          id: "a_terminal_fee",
          rowType: "terminal_fee",
          description: "Terminal Access Fee",
          quantity: 2,
          unitLabel: null,
          unitPrice: 45,
          monthlyRate: 45,
          totalMonthlyRate: 90,
          sourceLabel: "Default pricing",
        },
        {
          id: "a_overage",
          rowType: "overage",
          description: "Overage: Cost per 1.0 GB",
          quantity: null,
          unitLabel: "GB",
          unitPrice: 0.55,
          monthlyRate: 0.55,
          totalMonthlyRate: 0.55,
          sourceLabel: "Standard pricing",
        },
        {
          id: "a_support",
          rowType: "support",
          description: "iNet Support & Portal Access",
          includedText: [
            "24/7/365 support",
            "Customer portal access",
            "Usage and performance reporting",
          ],
          sourceLabel: "Standard pricing",
        },
      ],
      perKitRows: [
        {
          id: "a_perkit_50gb",
          rowType: "service",
          description: "50GB Data Block",
          quantity: 12,
          unitLabel: "blocks",
          unitPrice: 30,
          monthlyRate: 30,
          totalMonthlyRate: 360,
          sourceLabel: "Standard pricing",
        },
        {
          id: "a_perkit_500gb",
          rowType: "service",
          description: "500GB Data Block",
          quantity: 2,
          unitLabel: "blocks",
          unitPrice: 132,
          monthlyRate: 132,
          totalMonthlyRate: 264,
          sourceLabel: "Standard pricing",
        },
        {
          id: "a_perkit_terminal",
          rowType: "terminal_fee",
          description: "Terminal Access Fee",
          quantity: 10,
          unitLabel: null,
          unitPrice: 45,
          monthlyRate: 45,
          totalMonthlyRate: 450,
          sourceLabel: "Default pricing",
        },
        {
          id: "a_perkit_support",
          rowType: "support",
          description: "iNet Support & Portal Access",
          includedText: ["24/7/365 support", "Monitoring and portal access"],
          sourceLabel: "Standard pricing",
        },
      ],
      computed: {
        terminalAccessFeeDefault: 45,
        block50Default: 30,
        block500Default: 132,
        monthlyRecurringTotal: 1290,
      },
    },
    sectionB: {
      enabled: true,
      allowLineAdd: true,
      allowLineRemove: true,
      allowReorder: true,
      builderLabel: "Hardware and accessories",
      title: "Starlink equipment and accessories",
      introText: "The prices below reflect one-time hardware and accessory charges.",
      lineItems: [
        {
          id: "b_gen3_perf",
          sourceType: "standard",
          itemName: "Performance G3",
          itemCategory: "Terminal",
          terminalType: "Performance G3",
          quantity: 2,
          unitPrice: 1999,
          totalPrice: 3998,
          sourceLabel: "Starlink hardware pricing",
        },
        {
          id: "b_pipe_adapter",
          sourceType: "standard",
          itemName: "Performance G3 Pole Mount Adapter",
          itemCategory: "Mount Adapter",
          quantity: 2,
          unitPrice: 75,
          totalPrice: 150,
          sourceLabel: "Mounting accessories",
        },
        {
          id: "b_50m_cable",
          sourceType: "standard",
          itemName: "50 Meter Starlink Cable",
          itemCategory: "Cable",
          quantity: 2,
          unitPrice: 150,
          totalPrice: 300,
          sourceLabel: "Accessory catalog",
        },
        {
          id: "b_non_pen_mount",
          sourceType: "custom",
          itemName: "Non-Pen Mount",
          itemCategory: "Mount",
          quantity: 2,
          unitPrice: 500,
          totalPrice: 1000,
          description: "Non-penetrating mount option for fixed-site deployments.",
          sourceLabel: "Mounting accessories",
        },
      ],
      computed: {
        equipmentTotal: 5448,
      },
    },
    sectionC: {
      enabled: false,
      allowLineAdd: true,
      allowLineRemove: true,
      allowReorder: true,
      builderLabel: "Optional field services",
      title: "Optional field services",
      introText: "Use this section for travel, inspections, and installation pricing when needed.",
      lineItems: [
        {
          id: "c_site_ny",
          sourceType: "custom",
          description: "Site Inspection (Travel and labor) NY Location",
          quantity: 1,
          unitPrice: 856,
          totalPrice: 856,
          pricingStage: "budgetary",
          serviceCategory: "site_inspection",
          notes: "Budgetary allowance before site visit is completed.",
          sourceLabel: "Standard pricing",
        },
      ],
      computed: {
        serviceTotal: 856,
      },
    },
  },
  revisionHistory: [
    {
      version: "1.0",
      changeDetails: "Builder-first draft with live quote sections.",
    },
  ],
  internal: {
    quoteId: "quote_cz_usa_rct001",
    quoteStatus: "draft",
    internalNotes: "Catalog and defaults loaded for builder use.",
    crmOwnerLabel: "Nick Panyard",
    crmSyncReady: false,
    savedProposalId: "quote_cz_usa_rct001",
    workspaceOwnerId: "nick-panyard",
    workspaceOwnerName: "Nick Panyard",
  },
  integrations: {
    ...createDefaultIntegrationState(),
    quoteReferences: {
      account: {
        provider: "salesforce",
        entityType: "account",
        externalId: "001-demo-account",
        externalLabel: "CZ USA",
        lastSyncedAt: "2026-04-02T14:10:00Z",
      },
      contact: {
        provider: "hubspot",
        entityType: "contact",
        externalId: "201-demo-contact",
        externalLabel: "Scott Duncan",
      },
    },
    lastSyncSummary: "CRM references included for standalone proposal workflow.",
  },
  documentRules: {
    preserveTemplateLook: true,
    keepRowsTogether: true,
    keepSectionHeadingWithContent: true,
    preventRowSplitAcrossPages: true,
    avoidOrphanedSectionHeaders: true,
  },
};
