import type { QuoteRecord } from "@/app/lib/quote-record";

export const sampleQuoteRecord: QuoteRecord = {
  metadata: {
    proposalNumber: "RCT001",
    proposalDate: "April 2, 2026",
    revisionVersion: "1.0",
    documentTitle: "Managed Communications Services",
    documentSubtitle: "Budgetary Estimate Builder",
    customerShortName: "CZ USA",
    currencyCode: "USD",
    status: "draft",
    quoteType: "purchase",
  },
  customer: {
    name: "CZ USA",
    logoText: "CZ USA",
    contactName: "Chelsey J. Franklin",
    contactPhone: "830.249.8284",
    contactEmail: "cfranklin@westwardenv.com",
    addressLines: ["4 Shooting Club Road / PO Box 2205", "Boerne, TX 78006"],
  },
  inet: {
    name: "Infrastructure Networks",
    contactName: "Nick Panyard",
    contactPhone: "919.864.5912",
    contactEmail: "nick.panyard@inetlte.com",
    addressLines: ["Galleria Tower II", "5051 Westheimer, Suite 1700", "Houston, TX 77056"],
  },
  executiveSummary: {
    enabled: true,
    paragraphs: [
      "Use this builder to shape the commercial inputs that will later flow into the branded PDF package.",
      "For this pass, Section A and Section B are the live quoting areas, with a cleaner editor built around real line-item structures.",
      "The output below is intentionally operational and editable instead of trying to mimic the final PDF layout.",
    ],
  },
  sections: {
    sectionA: {
      enabled: true,
      allowLineAdd: true,
      allowLineRemove: true,
      allowReorder: true,
      builderLabel: "Monthly service pricing",
      mode: "pool",
      title: "Monthly Starlink Service Pricing",
      introText: "Choose either pooled bandwidth pricing or per-kit data blocks.",
      termMonths: 12,
      poolRows: [
        {
          id: "a_pool_500gb",
          rowType: "service",
          description: "500GB, US Pool for Starlink Service",
          quantity: 1,
          unitLabel: "pool",
          unitPrice: 200,
          monthlyRate: 200,
          totalMonthlyRate: 200,
          sourceLabel: "Sample quote record",
        },
        {
          id: "a_terminal_fee",
          rowType: "terminal_fee",
          description: "Terminal Access Fee (Per Kit)",
          quantity: 2,
          unitLabel: "kit",
          unitPrice: 45,
          monthlyRate: 45,
          totalMonthlyRate: 90,
          sourceLabel: "Confirmed default",
        },
        {
          id: "a_overage",
          rowType: "overage",
          description: "Overage: Per 1.0 GB",
          quantity: null,
          unitLabel: "GB",
          unitPrice: 0.55,
          monthlyRate: 0.55,
          totalMonthlyRate: null,
          sourceLabel: "Source proposal",
        },
        {
          id: "a_support",
          rowType: "support",
          description: "iNet Customer Support",
          includedText: [
            "NOC 24/7/365 Support",
            "Customer Portal Access",
            "Reports & Metrics via iNView Portal",
          ],
          sourceLabel: "Source proposal",
        },
      ],
      perKitRows: [
        {
          id: "a_perkit_50gb",
          rowType: "service",
          description: "50GB Data Block",
          quantity: 12,
          unitLabel: "blocks",
          unitPrice: 30,
          monthlyRate: 30,
          totalMonthlyRate: 360,
          sourceLabel: "Sample quote record",
        },
        {
          id: "a_perkit_500gb",
          rowType: "service",
          description: "500GB Data Block",
          quantity: 2,
          unitLabel: "blocks",
          unitPrice: 132,
          monthlyRate: 132,
          totalMonthlyRate: 264,
          sourceLabel: "Sample quote record",
        },
        {
          id: "a_perkit_terminal",
          rowType: "terminal_fee",
          description: "Terminal Access Fee (Per Kit)",
          quantity: 10,
          unitLabel: "kits",
          unitPrice: 45,
          monthlyRate: 45,
          totalMonthlyRate: 450,
          sourceLabel: "Confirmed default",
        },
        {
          id: "a_perkit_support",
          rowType: "support",
          description: "iNet Customer Support",
          includedText: ["Included", "24/7/365 monitoring support"],
          sourceLabel: "Source proposal",
        },
      ],
      computed: {
        terminalAccessFeeDefault: 45,
        block50Default: 30,
        block500Default: 132,
        monthlyRecurringTotal: 290,
      },
    },
    sectionB: {
      enabled: true,
      allowLineAdd: true,
      allowLineRemove: true,
      allowReorder: true,
      builderLabel: "Hardware and accessories",
      title: "Starlink equipment and accessories",
      introText: "Start with catalog items from the source workbook / mount guide and then adjust quantities or add custom rows.",
      lineItems: [
        {
          id: "b_gen3_perf",
          sourceType: "standard",
          itemName: "Starlink Performance Kit",
          itemCategory: "Terminal",
          terminalType: "Performance",
          quantity: 2,
          unitPrice: 1999,
          totalPrice: 3998,
          sourceLabel: "Starlink hardware notes + sample proposal",
        },
        {
          id: "b_pipe_adapter",
          sourceType: "standard",
          itemName: "Starlink Pipe Adapter",
          itemCategory: "Mount Adapter",
          quantity: 2,
          unitPrice: 75,
          totalPrice: 150,
          sourceLabel: "Sample proposal / mount guide stub",
        },
        {
          id: "b_50m_cable",
          sourceType: "standard",
          itemName: "50 Meter Starlink Cable",
          itemCategory: "Cable",
          quantity: 2,
          unitPrice: 150,
          totalPrice: 300,
          sourceLabel: "Sample proposal / accessories workbook stub",
        },
        {
          id: "b_non_pen_mount",
          sourceType: "custom",
          itemName: "Non-Pen Mount",
          itemCategory: "Mount",
          quantity: 2,
          unitPrice: 500,
          totalPrice: 1000,
          description: "Placeholder mount row until exact mount source extraction is completed.",
          sourceLabel: "Mount guide stub",
        },
      ],
      computed: {
        equipmentTotal: 5448,
      },
    },
    sectionC: {
      enabled: false,
      allowLineAdd: true,
      allowLineRemove: true,
      allowReorder: true,
      builderLabel: "Optional field services",
      title: "Optional field services",
      introText: "Keep this section as a later expansion area for travel, inspections, and install support.",
      lineItems: [
        {
          id: "c_site_ny",
          sourceType: "custom",
          description: "Site Inspection (Travel and labor) NY Location",
          quantity: 1,
          unitPrice: 856,
          totalPrice: 856,
          pricingStage: "budgetary",
          serviceCategory: "site_inspection",
          notes: "Budgetary allowance before site visit is completed.",
          sourceLabel: "Sample proposal",
        },
      ],
      computed: {
        serviceTotal: 856,
      },
    },
  },
  revisionHistory: [
    {
      version: "1.0",
      changeDetails: "Builder-first draft with live quote sections.",
    },
  ],
  internal: {
    quoteId: "quote_cz_usa_rct001",
    quoteStatus: "draft",
    internalNotes: "Source-driven catalog is still partly stubbed until workbook/doc extraction is completed.",
  },
  documentRules: {
    preserveTemplateLook: true,
    keepRowsTogether: true,
    keepSectionHeadingWithContent: true,
    preventRowSplitAcrossPages: true,
    avoidOrphanedSectionHeaders: true,
  },
};
